---
apiVersion: v1
kind: Service
metadata:
  name: n8n
  namespace: {{ .Values.namespace.name }}
  labels:
    app: n8n
    component: n8n
spec:
  type: {{ .Values.n8n.service.type }}
  selector:
    app: n8n
    component: n8n
  ports:
    - name: http
      protocol: TCP
      port: {{ .Values.n8n.service.port }}
      targetPort: http
      {{- if eq .Values.n8n.service.type "NodePort" }}
      nodePort: {{ .Values.n8n.service.nodePort }}
      {{- end }}
