---
apiVersion: v1
kind: Secret
metadata:
  name: n8n-secrets
  namespace: {{ .Values.namespace.name }}
  labels:
    app: n8n
type: Opaque
stringData:
  N8N_BASIC_AUTH_PASSWORD: {{ .Values.secrets.basicAuthPassword | quote }}
  N8N_ENCRYPTION_KEY: {{ .Values.secrets.encryptionKey | quote }}
  N8N_API_KEY: {{ .Values.secrets.n8nApiKey | quote }}
  MCP_AUTH_TOKEN: {{ .Values.secrets.mcpAuthToken | quote }}
