apiVersion: v1
kind: Service
metadata:
  name: {{ include "n8n.serviceName" . }}
  namespace: {{ include "n8n.namespace" . }}
  {{- with .Values.service.labels }}
  labels:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "n8n.selector" . | nindent 4 }}
  ports:
    - port: {{ .Values.port }}
      targetPort: {{ .Values.port }}
      protocol: TCP
      {{- if .Values.portName }}
      name: {{ .Values.portName }}
      {{- end }}
